[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
python_files = tests.py test_*.py *_tests.py
addopts =
    --reuse-db
    --nomigrations
    -ra
    --cov=apps
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=0
testpaths = apps

filterwarnings = ignore::DeprecationWarning