# Generated by Django 5.2.17 on 2026-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='priority_rank',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Priority'), (2, 'Staff')], default=0, help_text='Higher rank = shown first in Discover, Daily Picks, Likes.'),
        ),
    ]
