# Generated by Django 5.2.17 on 2026-10-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_priority_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="priority_rank",
        ),
        migrations.AddField(
            model_name="profile",
            name="featured_note",
            field=models.CharField(
                blank=True,
                help_text="Optional tagline shown on featured profiles (e.g., 'Editors's Pick').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured profiles appear first in Discover and Daily Picks.",
            ),
        ),
    ]
