# Generated by Django 5.2.17 on 2026-09-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='profile_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='profile_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['liker', 'likee'], name='likes_liker_i_d45b7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(('liker', models.F('likee')), _negated=True), name='prevent_self_like'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'likee')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('profile_a', 'profile_b')},
        ),
    ]
