# Generated by Django 5.2.17 on 2026-09-28 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_received', to='profiles.profile')),
                ('passer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_given', to='profiles.profile')),
            ],
            options={
                'db_table': 'passes',
                'indexes': [models.Index(fields=['passer', 'passed'], name='passes_passer__5cc4bf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('passer', models.F('passed')), _negated=True), name='prevent_self_pass')],
                'unique_together': {('passer', 'passed')},
            },
        ),
    ]
