# Generated by Django 5.2.17 on 2026-09-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='messages_match_i_33be21_idx'),
        ),
    ]
